baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "North Brooklyn Angels"
paginate = 10
enableGitInfo = true

# Need to raise this because it times out when building on GitHub
timeout = 300000

# disableKinds = ["RSS",  "sitemap"]

contentDir = "../content"

[permalinks]
    "in-the-news" = "/in-the-news/:year/:month/:slug/"

[taxonomies]
    source = "source"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
    [markup.tableOfContents]
        startLevel = 1

[imaging]
resampleFilter = "Lanczos"
quality = 80
anchor = "smart"
bgColor = "#ffffff"

[params]
# Meta description
Description = "North Brooklyn Angels is a volunteer-powered nonprofit in Greenpoint, Williamsburg, and Bushwick, Brooklyn. Since 2017, we've served 750,000+ hot meals through our Mobile Soup Kitchen, connected 75+ families with essential baby gear through Little Angels, and launched Live Local to help neighbors navigate NYC's affordable housing lottery. 95% volunteer-powered. Neighbors helping neighbors."
# Meta keywords
Keywords = "soup kitchen, mobile soup kitchen, north brooklyn angels, nba, charity"